name: "CI"

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
  push:
    branches: ['develop', 'master']

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  php-test:
    strategy:
      fail-fast: true
      matrix:
        php: [8.1, 8.2]

    name: pest-php-${{ matrix.php }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install composer dependencies
        uses: ramsey/composer-install@v2

      - name: Execute tests (Unit and Feature tests) via PHPUnit
        run: php artisan test
