name: "CI"

on:
  pull_request:
    types: [ opened, synchronize, reopened, ready_for_review ]
  push:
    branches: [ 'develop', 'master' ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  laravel-test:
    strategy:
      fail-fast: true
      matrix:
        php: [ 8.2 ]

    name: "Pest (PHP ${{ matrix.php }})"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create .env file
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}

      - name: Get composer cache
        uses: actions/cache@v3
        id: vendor
        with:
          path: |
            **/vendor
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}-${{ matrix.php }}

      - name: Install composer dependencies
        uses: ramsey/composer-install@v2

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 20.x

      - name: Get node version
        id: node
        run: |
          echo "::set-output name=version::$(node -v)"

      - name: Get node_modules cache
        uses: actions/cache@v3
        id: node_modules
        with:
          path: |
            **/node_modules
          key: ${{ runner.os }}-node_modules-${{ hashFiles('**/yarn.lock') }}-${{ steps.node.outputs.version }}

      - name: Compile assets
        run: |
          yarn install
          yarn build

      - name: Generate encryption key
        run: php artisan key:generate

      - name: Set directory permissions
        run: chmod -R 777 storage bootstrap/cache

      - name: Create Database
        run: |
          mkdir -p database
          touch database/database.sqlite

      - name: Execute tests (Unit and Feature tests) via Pest
        env:
          DB_CONNECTION: sqlite
          DB_DATABASE: database/database.sqlite
        run: php artisan test --coverage --coverage-clover=coverage-report.xml

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
