name: "CI"

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
  push:
    branches: ['develop', 'master']

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  php-test:
    strategy:
      fail-fast: true
      matrix:
        php: [8.1, 8.2]

    name: pest-php-${{ matrix.php }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up PHP
          uses: shivammathur/setup-php@v2
          with:
            php-version: ${{ matrix.php }}

      - name: Install composer dependencies
        uses: ramsey/composer-install@v2

      - name: Create .env file
        run: cp .env.example .env

      - name: Generate encryption key
        run: php artisan key:generate

      - name: Execute tests (Unit and Feature tests) via PHPUnit
        run: php artisan test
