name: "CI"

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
  push:
    branches: ['develop', 'master']

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  php-test:
    strategy:
      fail-fast: true
      matrix:
        php: [8.1, 8.2]

    name: pest-php-${{ matrix.php }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}

      - name: Install composer dependencies
        uses: ramsey/composer-install@v2

      - name: Create .env file
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"

      - name: Generate encryption key
        run: php artisan key:generate

      - name: Set directory permissions
        run: chmod -R 777 storage bootstrap/cache

      - name: Create Database
        run: |
          mkdir -p database
          touch database/database.sqlite

      - name: Execute tests (Unit and Feature tests) via Pest
        env:
          DB_CONNECTION: sqlite
          DB_DATABASE: database/database.sqlite
        run: php artisan test
